[accounts.one]
usercode="YourAccount"
password="YourPassword"
isp="campus"
interfaces=[ "macvlan1","macvlan2","macvlan3","macvlan4" ]
[accounts.two]
usercode="YourAccount"
password="YourPassword"
isp="cm"
interfaces=[ "macvlan5","macvlan6","macvlan7","macvlan8" ]